import React from 'react';
import { Column, Row, Subhead, Text } from 'rebass';

const bankA = [
  'Blue Dolphin BC',
  'Chord Play RD',
  'Heaven Pad KA',
  'Rich Rises DK',
  'Hammer Bass KA',
  'JunoProximityMS',
  'Sweep & Fold RD',
  'Robbie2 RBr',
  'Outer Rim JD',
  'In My Spot BC',
  'TensionBass RD',
  'Bullish DG',
  'Symphonia KA',
  'Mono Cloud DK',
  'Technodisco JD',
  'AfterGlow RD',
  'Brassy KA',
  '2Wheel Drive RB',
  'EventHorizen RD',
  '1973 RD',
  'MouseChord DK',
  'Phat Morph KA',
  'BlissPad RD',
  'Up In Clouds RD',
  'Dark Apostle JD',
  "Gianni'Arp SG",
  'Slasher DK',
  'ass Punch DK',
  'TineEP1 DG',
  'Massive KA',
  'BOC Pad RD',
  'Juppy Synth KA',
  'Helix Repeat RB',
  'HammondCrunchDG',
  'Nightdrive BC',
  'Brass Pad BC',
  'Influx Pad KA',
  'Tundra RD',
  'CS Strings KA',
  'Nice Pad KA',
  'Echo Base JD',
  'Arptastic2 RB',
  'Movement ST',
  'Poly Dream RD',
  "Funkin'FilthyBC",
  'Battleground BC',
  'SynthBass 3 KA',
  'Ethereal Pad RD',
  'Flutter Seq DK',
  'InTheAir1KA',
  'ModDecimator JD',
  'Rich Chords RD',
  'DeepEP4 BC',
  'Human Pad KA',
  'Chord Pulse RD',
  'Wide StringsST',
  'ReedEP1 DG',
  'Abyss JD',
  'Pwm Pad RB',
  'Slow Glide RD',
  'Movement BC',
  'Punch Bass KA',
  'DreamSeq RD',
  'Soft Mono DK',
  'ElecKoto DG',
  'Zero Bass JD',
  'Flead RB',
  'Planet Zion RD',
  'Arp+Seq BC',
  'Rock On KA',
  'Fairy Tales RD',
  'Lost Verb',
  'Bilitis 1 KA',
  'Groovy! ST',
  'GlassPoly RD',
  'Top Bass BC',
  'Funky Lead KA',
  'Sweet Pulse RD',
  'Soft Fifth DK',
  'Spaceman KA',
  'Chiffy Arp ST',
  'Alien Shift RD',
  'Mean Lead BC',
  'Rhythm Steps KA',
  'ReedEP3 DG',
  'PhaseClav DG',
  'Dream Pad KA',
  'Coil Soup ST',
  '2PSweepPad DG',
  'DeepCheez BC',
  'Cl&OpHats DG',
  'Warm BD DG',
  'Sub Monster ST',
  'Sync Lead RD',
  'Squarp BC',
  'Sawyer Lead KA',
  'Rez BD DG',
  'Berlin KA',
  'Latey Bass ST',
  '0 Rotary RhodesDG',
  'HerbieComp DG',
  'Iridescent BC',
  'Field Space RD',
  'Snr1 DG',
  'Flange Lead KA',
  'Six Oh OnesiDK',
  'MainBrass DG',
  'Magic Key RD',
  'DeEP2 BC',
  '0 Soft Swells DK',
  'KApro Pad KA',
  'Dream Arp JD',
  'Old School RD',
  'String Pad KA',
  'Polygroove BC',
  'TineEP2 DG',
  'ChordCrunch DK',
  'Miami Bass KA',
  'Jumpy! ST',
  '0 Juice3DG',
  'Moving Along RD',
  'Woody Bass',
  'Morpholog KA',
  'Cyber Pad KA',
  'EtheriArp BC',
  'CloudCastle RD',
  'Sparkle Lead RD',
  'RubberEP'
];

const DeepMind12Page = props => {
  return (
    <div>
      <Row>
        <Column>
          <Subhead mb={3}>Bank A</Subhead>
          {bankA.map(item => <Text mb={1}>{item}</Text>)}
        </Column>
        <Column>
          <Subhead>Bank C</Subhead>
        </Column>
        <Column>
          <Subhead>Bank D</Subhead>
        </Column>
      </Row>
    </div>
  );
};

DeepMind12Page.propTypes = {};

export default DeepMind12Page;
