export const bankA = [
  'Blue Dolphin BC',
  'Chord Play RD',
  'Heaven Pad KA',
  'Rich Rises  DK',
  'Hammer Bass KA',
  'JunoProximityMS',
  'Sweep & Fold RD',
  'Robbie2 RBr',
  'Outer Rim JD',
  'In My Spot BC',
  'TensionBass RD',
  'Bullish      DG',
  'Symphonia KA',
  'Mono Cloud  DK',
  'Technodisco JD',
  'AfterGlow RD',
  'Brassy KA',
  '2Wheel Drive RB',
  'EventHorizen RD',
  '1973 RD',
  'MouseChord DK',
  'Phat Morph KA',
  'BlissPad RD',
  'Up In Clouds RD',
  'Dark Apostle JD',
  "Gianni'Arp SG",
  'Slasher     DK',
  'ass Punch DK',
  'TineEP1 DG',
  'Massive KA',
  'BOC Pad RD',
  'Juppy Synth KA',
  'Helix Repeat RB',
  'HammondCrunchDG',
  'Nightdrive BC',
  'Brass Pad BC',
  'Influx Pad KA',
  'Tundra RD',
  'CS Strings KA',
  'Nice Pad KA',
  'Echo Base JD',
  'Arptastic2 RB',
  'Movement ST',
  'Poly Dream RD',
  "Funkin'FilthyBC",
  'Battleground BC',
  'SynthBass 3 KA',
  'Ethereal Pad RD',
  'Flutter Seq DK',
  'In The Air 1 KA',
  'ModDecimator JD',
  'Rich Chords RD',
  'DeepEP4 BC',
  'Human Pad KA',
  'Chord Pulse RD',
  'Wide StringsST',
  'ReedEP1 DG',
  'Abyss JD',
  'Pwm Pad RB',
  'Slow Glide RD',
  'Movement BC',
  'Punch Bass KA',
  'DreamSeq RD',
  'Soft Mono   DK',
  'Bank A',
  'ElecKoto     DG',
  'Zero Bass JD',
  'Flead RB',
  'Planet Zion RD',
  'Arp+Seq BC',
  'Rock On KA',
  'Fairy Tales RD',
  'Lost Verb   DK',
  'Bilitis 1 KA',
  'Groovy! ST',
  'GlassPoly RD',
  'Top Bass BC',
  'Funky Lead KA',
  'Sweet Pulse RD',
  'Soft Fifth  DK',
  'Spaceman KA',
  'Chiffy Arp ST',
  'Alien Shift RD',
  'Mean Lead BC',
  'Rhythm Steps KA',
  'ReedEP3 DG',
  'PhaseClav   DG',
  'Dream Pad KA',
  'Coil Soup ST',
  '2PSweepPad   DG',
  'DeepCheez BC',
  'Cl&OpHats   DG',
  'Warm BD      DG',
  'Sub Monster ST',
  'Sync Lead RD',
  'Squarp BC',
  'Sawyer Lead KA',
  'Rez BD       DG',
  'Berlin KA',
  'Latey Bass ST',
  'Rotary RhodesDG',
  'HerbieComp   DG',
  'Iridescent BC',
  'Field Space RD',
  'Snr1         DG',
  'Flange Lead KA',
  'Six Oh OnesiDK',
  'MainBrass DG',
  'Magic Key RD',
  'DeEP2 BC',
  'Soft Swells DK',
  'KApro Pad KA',
  'Dream Arp JD',
  'Old School RD',
  'String Pad KA',
  'Polygroove BC',
  'TineEP2 DG',
  'ChordCrunch DK',
  'Miami Bass KA',
  'Jumpy! ST',
  'Juice3DG',
  'Moving Along RD',
  'Woody Bass   DG',
  'Morpholog KA',
  'Cyber Pad KA',
  'EtheriArp BC',
  'CloudCastle RD',
  'Sparkle Lead RD',
  'RubberEP'
];

export const bankB = [
  'PluckPad BC',
  '2P Strings BC',
  'Britelead BC',
  'PhaseVox BC',
  'Hollow Arp BC',
  'Flunk BC',
  'Mean Lead BC',
  'Enigmatiq BC',
  'Brass BC',
  'Keytar BC',
  'EtheriArp BC',
  'Big Muff BC',
  'Clatter BC',
  'Mindful BC',
  'Flead BC',
  'Pure Lead BC',
  "Funkin'FilthyBC",
  'Heimlich BC',
  'Pushover BC',
  'BackdrpStr BC',
  'Hourglass BC',
  'Brass Pad BC',
  'JarpanBC',
  'Kinda Creepy BC',
  "Poppin' BC",
  'SoftVox BC',
  'DeepLeadBC',
  'OD Bass BC',
  'DeEP BC',
  'DeEP2 BC',
  'Top Bass BC',
  'TouchXstlBC',
  'In My Spot BC',
  'DeepCheez BC',
  'Bowed Pad BC',
  'Europa BC',
  'Snare BC',
  'Zap Kick BC',
  'MW Hats BC',
  "Punchin'BC",
  'Arp+Seq BC',
  'RotarOrgMW BC',
  'Cheap Lead BC',
  'Aeriel BC',
  'Wet Poly BC',
  'Simple PWM BC',
  'Big Sync BC',
  'Polygroove BC',
  'Claps BC',
  'Touch Acid BC',
  'Backflip BC',
  'Fraptur BC',
  'FuturHats BC',
  'ModWmeGently BC',
  'HolloVox BC',
  'Torn BC',
  'Sync2bar BC',
  'Rezome BC',
  'Harpeen BC',
  'Trickldown BC',
  'Unsubtle BC',
  'Smoothie BC',
  'Glass Keys BC',
  'BigmeARP BC',
  'Bank B',
  'Plucksync BC',
  'Tambourine BC',
  'TwonK BC',
  'Big Toms BC',
  'DigitARP BC',
  'ClassicFunk BC',
  'SyncSeq BC',
  'Blue Dolphin BC',
  'CottonBuds BC',
  'Reversi BC',
  'Chiffle BC',
  'Tresco BC',
  'Electrodidge BC',
  'Epicentre BC',
  'Nightdrive BC',
  'Fragile Arp BC',
  'Pitchy Poly BC',
  'Iridescent BC',
  'DeepJam BC',
  'Gant Bay BC',
  'TriassicDawn BC',
  'AngelArp BC',
  'BubbleKeys BC',
  'Untuned BC',
  'Phalangi BC',
  'Echology BC',
  'Keytar2 BC',
  'SpitnPolish BC',
  'Formula12 BC',
  'Data Soup BC',
  'Squarp BC',
  'Marcato BC',
  'Movement BC',
  'Movement2BC',
  'Bubble Saw BC',
  'Arp City BC',
  'Kardashia BC',
  'Bow Bottles BC',
  'Warm Horns BC',
  'Bright Piano BC',
  'Chorus Piano BC',
  'Trem E.P. BC',
  'DeepEP4 BC',
  'Puffin BC',
  'No Hurry BC',
  'RadioDM1.2am BC',
  'Crztl Rez BC',
  'Cyberverb BC',
  'Robochoir BC',
  'Undersync BC',
  'Synchole BC',
  'Fatboy BC',
  'Egg Cups BC',
  'Too Late BC',
  'Theremind BC',
  'Sync City BC',
  'Snap Bass BC',
  'Warm Bass BC',
  'Undercurrent BC',
  'Risers BC',
  'Ocean Jewel BC',
  'Battleground BC',
  'Attack Pad BC',
  'PluckyBasstd'
];

export const bankC = [
  'Bass Pong RD',
  'Soft Tines RD',
  'CloudCastle RD',
  'ClassicBass RD',
  'SwellArp RD',
  'Arp Nebula RD',
  'BubbleSwarm RD',
  'TexturePluck RD',
  'Scrible Pad RD',
  'Glitch Glitter R',
  'Changin ColorRD',
  'AlienSpinnersRD',
  'Sweep & Fold RD',
  'Magestic RD',
  'Ocean Dream RD',
  'Pulse Bass RD',
  'Drift & Fall RD',
  'Animater Pad RD',
  'Weaver Pad RD',
  'Spike Bass RD',
  'Spin Space RD',
  'Riser Bass RD',
  'Rise Up RD',
  'Emeralds RD',
  'Arp In SpringRD',
  'Blaze Acid RD',
  'Star Lights RD',
  'Murk Bass RD',
  'Evergreen RD',
  'Plink Pluck RD',
  'Soft Tones RD',
  'Glitchnoria RD',
  'BreezePad RD',
  'WeaverBass RD',
  'Neptune Pad RD',
  'Double Bass RD',
  'Poly Arp RD',
  'Moss Pad RD',
  '5th Pad RD',
  'Moogy Lead RD',
  'Shooting StarRD',
  'Reverse Pad RD',
  'King Arp RD',
  'Wah Wah Pad RD',
  'Warm Swarm RD',
  'Classic Bass RD',
  'Random Seq RD',
  'Cloud Pad RD',
  'Mad Lab RD',
  'Wreak & Hold RD',
  'Anthem Arp RD',
  'Electro Lead RD',
  'Rotor Bass RD',
  'Sparkle Bass RD',
  'Fairy Tales RD',
  'BOC Pad RD',
  'Tom Drums RD',
  'Chord Morph RD',
  'BirchWood RD',
  'EDM SirenLeadRD',
  'Ice Cave   RD',
  'Ocean ExploreRD',
  'BlueArp RD',
  'Atari Lead RD',
  'Bank C',
  'Sci-Fi AtmosRD',
  'Nature Pad RD',
  'Motor Bass RD',
  'Fly Away RD',
  'Chord Pulse RD',
  'Evolution PadRD',
  'Movie Pad RD',
  'CrystalWatersRD',
  'Sparkle Lead RD',
  'Glass  Bass RD',
  'Busy Streets RD',
  'Chord Play RD',
  'Passing Time RD',
  'Moody Piano RD',
  'Tiny Science RD',
  'Slow Space RD',
  'Stack Bass RD',
  'Signal Pad RD',
  'Ethereal Pad RD',
  'Mary Time RD',
  'Dive Abyss RD',
  'Sputter Pad RD',
  'Smooth Bass RD',
  'Waddle Pad RD',
  'Treasure RD',
  'Cluster Pad RD',
  'Sweet Pulse RD',
  'Spin Space RD',
  'Super Nova RD',
  'Ozz Land RD',
  'Blotter Pad RD',
  'Air Pad RD',
  'Burrow Bass RD',
  'Softly FallinRD',
  'Contemplate RD',
  'TransmissionsRD',
  'Bowl Bass RD',
  'Hold & Swirl RD',
  'Night PassageRD',
  'Stacked RD',
  'Tundra RD',
  'Mountain LeadRD',
  'BlissPad RD',
  'New Life RD',
  'Dot Pulse RD',
  'Mysteriou RD',
  'Poly Dreams  RD',
  'Big Lead RD',
  'Years After RD',
  'TensionBass RD',
  'Vice Bass RD',
  'Voodoo Lead RD',
  'Memoir RD',
  'Dance In TimeRD',
  'Nature Pad RD',
  'Simple Bass RD',
  'Estate Ping RD',
  'Field Space RD',
  'In the Val1eyRD',
  'PolyTime RD',
  'Spectrum Pad RD',
  'Bloom Lead RD',
  'Downwards RD',
  'DreamSeq RD'
];

export const bankD = [
  'JP-Synth  KA',
  'Modular   KA',
  'Rhythm Pad KA',
  'Ambisphere KA',
  'LFO Pad KA',
  'Ghost Pad KA',
  'Touch Me KA',
  'Dream Pad KA',
  'Pulsar KA',
  'Synbell KA',
  'Fat Bass KA',
  'Phat Poly KA',
  'Space Talk KA',
  'Pure Phat KA',
  'Bass Drone KA',
  'The Pig KA',
  'Pulse Pad KA',
  'Crunch KA',
  'Berlin KA',
  'Wavetables KA',
  'Free Run KA',
  'Mod Me KA',
  'Warm Pad KA',
  'Brass Pad KA',
  'KApro Pad KA',
  'Phatty KA',
  'Low Boost KA',
  'Use M-Wheel KA',
  'Old Days KA',
  'Run Blade RunKA',
  'VCF Sweep KA',
  'Poly Sync KA',
  'Modular DroneKA',
  'Just Filter KA',
  'So Lucky KA',
  'Slow Pad KA',
  'Analogon KA',
  'Flange Lead KA',
  'Mod XY Lead KA',
  'My Phat Pad KA',
  'Air Pad KA',
  'Space Tone KA',
  'LFO FX KA',
  'Robot Dreams KA',
  'Bilitis 1 KA',
  'Bilitis 2 KA',
  'Tangerine KA',
  'Sweeper KA',
  'Dream Pad 1 KA',
  'Dream Pad 2 KA',
  'Heaven Pad KA',
  'Heartbeat KA',
  'Vectoria KA',
  'Dub Bass KA',
  'S&H FX KA',
  'Juppy Synth KA',
  '1984 Pad KA',
  'Deep Pad KA',
  'Ambie Pad KA',
  'Dark Low KA',
  'Morph Pad KA',
  'Apollon KA',
  'Drone KA',
  'Daspeco KA',
  'Bank D',
  'Elec Perc KA',
  'Lush Pad KA',
  'Lacy Pad KA',
  'String Pad KA',
  'Pop Synth KA',
  'Poly Synth KA',
  'Choir Pad KA',
  'Brass KA',
  'Sympholog KA',
  'Spaceman KA',
  'Unison Bass KA',
  'Hammer Bass KA',
  'Distorbia KA',
  'Atmos Pad KA',
  'Modular Fun KA',
  'KARMA Pad KA',
  'Wavestepper KA',
  'Wallop KA',
  'Symphonia KA',
  'Echo Pad KA',
  'Move On KA',
  'Dark Pad KA',
  'Toy Synth KA',
  'Wires LFO KA',
  'Morpholog KA',
  'Dark PercularKA',
  'Spheres KA',
  'Move Wheel KA',
  'Retro Pad KA',
  'Shorty KA',
  'Miami Bass KA',
  'Cheesy Organ KA',
  'Electro CelloKA',
  'Echo Keys KA',
  'Double Lead KA',
  'Perc FX KA',
  'Bass Drum KA',
  'Aggro Lead KA',
  'Sweep Pad KA',
  'Pluck On KA',
  'Analog Organ KA',
  'Church Organ KA',
  'JP Lead KA',
  'JD Lead KA',
  'Mind Control KA',
  'A-Piano KA',
  'Try Wheel KA',
  'Synergy KA',
  'Percular KA',
  'Sleak Pad KA',
  'Noise Wheel KA',
  'Real Analog KA',
  'Fluty Lead KA',
  'Echolator KA',
  'Nice Pad KA',
  'Kitara Pad KA',
  'Vibro Pad KA',
  'Odykey KA',
  'In The Air 1 KA',
  'In The Air 2 KA',
  'MOD Dreams KA',
  'Serial Synth KA',
  'Resonator KA',
  'Numan Pad KA'
];

export const bankE = [
  'Mogae Bass ST',
  'With Pulse ST',
  'Latey Bass ST',
  'The Scream ST',
  'Sync Bass ST',
  'Sub Monster ST',
  'Acid Arap ST',
  'SuperSawSwelST',
  'Rippin ST',
  'Jumpy! ST',
  'Arpista ST',
  'Harpeggio  ST',
  'EdgeinSpaceST',
  'Starpy ST',
  'Coil Soup ST',
  'Chiffy Arp ST',
  'ClassicRand ST',
  'Groovy! ST',
  'Vibra-Arp ST',
  'Chord Arp ST',
  'Wide StringsST',
  'Warm StringsST',
  'Softness ST',
  'Movement ST',
  'Soundtrack16ST',
  'Sharmonia ST',
  'Stringbow ST',
  'D`accord ST',
  'Safe Haven ST',
  'EbowverdriveST',
  'Brasss ST',
  'ObligiclavST',
  'CeePee ST',
  'How Hi?ST',
  'M Box ST',
  'Sinty ST',
  '12 Sirens ST',
  'MOD WHEEL! ST',
  'Nailon ST',
  'Rotary RhodesDG',
  'KnobconPad STG',
  "Gianni'Arp SG",
  'PitchModSeqehMS',
  'JunoGravimityMS',
  'Tundra MS',
  'JunoProximityMS',
  'PhaseClav   DG',
  'MartinsStr1 MS',
  'Warm Pad DG',
  'Janes1str JC',
  'Drops Patch MS',
  'MartinsSatellMS',
  'MSfault MS',
  "St Paul's DK",
  'Pertwee DK',
  'Hartnell DK',
  'Baker DK',
  'THX-12       RB',
  'BadAssKick RB',
  'Arptastic2 RB',
  'Pwm Pad RB',
  'Juice DG',
  '2Wheel Drive RB',
  'ThereShimmer RB',
  'Bank E',
  'ThereminShimRB',
  'Flead RB',
  'New Dawn   RB',
  'Square Bass RB',
  'Morph Bass RB',
  'PressPad RB',
  'Hammer Bass2 PS',
  'Danger Will PS',
  'Skyscraper RBr',
  'Robbie1 RBr',
  'GatedPad RB',
  'Spacelay RB',
  'Hall Pad RB',
  'Robbie2 RBr',
  'CalumsMachineRB',
  '1540FW PS',
  'PhantasmFM RB',
  'Punch N Judy RB',
  'LushPad RB',
  'DarkPad PS',
  'Shining RB',
  'MusicBox PS',
  'Ice Age RB',
  'GardenParty RB',
  'Helix Repeat RB',
  'Echo Base JD',
  'HamlAnno JD',
  'Sloppy Mod CD',
  'Zero Bass JD',
  'Fore Bode JD',
  'Dark Grace JD',
  'Spaced Organ JD',
  'Mod Beats JD',
  'New Day JD',
  'Outer Rim JD',
  'Dream Arp JD',
  'Slow Roller JD',
  'Dark Rise JD',
  'Deephaus JD',
  'Deephouse JD',
  'Endless Sea JD',
  'Eastish JD',
  'Hill Silent JD',
  'Arp Roll JD',
  'Neuro Pad JD',
  'Scratci JD',
  'Teleport JD',
  'ModDecimator JD',
  'Blood Glitch JD',
  'Dirge JD',
  'Bubbler! JD',
  'Bass Arp JD',
  'Excited RobotJD',
  'ConstellationJD',
  'Dark Apostle JD',
  'Bombobass JD',
  'Abyss JD',
  'Teletran JD',
  'Slow Pass JD',
  'Technodisco JD',
  'DataJungle JD',
  'MachinelbowJD',
  'Darkreece JD',
  'Boxer JD'
];

export const bankF = [
  'Old School RD',
  'Busy HighwaysRD',
  'Sync Lead RD',
  'Blast Off RD',
  'Glass Pad RD',
  'Litter Bass RD',
  'Reflector RD',
  'R2D2 Talk RD',
  'StoryTime RD',
  'AlterArp RD',
  'Drum Seq RD',
  'Polynomial RD',
  'Click Bass RD',
  'Math Pad RD',
  'Evolving Pad RD',
  'Drag & Roll RD',
  'Wiggle Worm RD',
  'DelicateDanceRD',
  'Sync Scatter RD',
  'Texture Poly RD',
  '1973 RD',
  'Droplet Pad RD',
  'MartianLandinRD',
  'Geomtry Pad RD',
  'Ripple Decay RD',
  'Helicopters RD',
  'BeatEnvelopesRD',
  'Particle Pad RD',
  'Tom Drums RD',
  'Magic Key RD',
  'SuperSync RD',
  'Up In Clouds RD',
  'Soft Ghosts RD',
  'StairWays RD',
  'Trap Lead RD',
  'CrissCross RD',
  'Micro Macro RD',
  'Chord Play RD',
  'GlassPoly RD',
  'Glider RD',
  'Smoke Trails RD',
  'Modular Pod RD',
  'Mellow MeadowRD',
  'Rich Chords RD',
  'Smooth Pad RD',
  'Arpy Lead RD',
  'Night Skys RD',
  'Compute This RD',
  'Dark Blood RD',
  'At Dark RD',
  'Tight StringsRD',
  'Enchanted RD',
  'Mesh Bass RD',
  'SFX-Rise RD',
  '808 State RD',
  'HeavyHitter RD',
  'Evening LightRD',
  'Spears RD',
  'Sparce Lead RD',
  'Moving Along RD',
  'Bow Glass RD',
  'Time & Place RD',
  'Sync N Sync RD',
  'Weeby Pads RD',
  'Bank F',
  'Winter Pad RD',
  'Piano Amber RD',
  'Boxed Arp RD',
  'Bleepy Lead RD',
  'Mods Bass RD',
  'Lead Spacer RD',
  'Deep Drone RD',
  'Brick Bass RD',
  'Metal Mod RD',
  'Sky Fly RD',
  'Slow Glide RD',
  'Chord Heaven RD',
  'Royal Arp RD',
  'Pearl Drops RD',
  'SpinningPulseRD',
  'ShootingStar RD',
  'Swamp Pad RD',
  'AfterGlow RD',
  'EventHorizen RD',
  'Old Film RD',
  'Hexagon Sun RD',
  'HarmonySwarm RD',
  'Dub Techno RD',
  'Fushia RD',
  'Sputter Pad RD',
  'Hold & Pulse RD',
  'Aurora RD',
  'Ratchet Beat RD',
  'Ring Arp RD',
  'Epic Bass RD',
  '5ths Seqence RD',
  'Spin Cycles RD',
  'Spike Bass RD',
  'Enchant RD',
  'Spash Effect RD',
  'Pine Lead RD',
  'Fabrics RD',
  'Cross Mods RD',
  'Scrabble RD',
  'Mod-Matrix RD',
  'Mod Drums RD',
  'Techre Splat RD',
  'Abstracts RD',
  'Modular Lava RD',
  'Planet Zion RD',
  'Alien Shift RD',
  'Spreader RD',
  'Morning Sun RD',
  'Whale Pad RD',
  'Noodle Space RD',
  'In The Clear RD',
  'Analog Perc RD',
  'Nasal Bass RD',
  'Mecury Piano RD',
  'Poly Dream RD',
  'Aerial RD',
  'Crystalline RD',
  'Elektra Pad RD',
  'H20 Pad RD',
  'Saw Cutter RD',
  'River Run RD',
  'Thinking RD',
  'Creep Up BassRD',
  'Sine Piano R'
];

export const bankG = [
  'Storm Pad KA',
  'CS Strings KA',
  'Warm Pad KA',
  'Analog Bell KA',
  'Morph Lead KA',
  'Reverse Pad KA',
  'SkyFy Pad KA',
  'Cloud Pad KA',
  'Phat Morph KA',
  'Delay Lead KA',
  'Spinners KA',
  'Bagpipe KA',
  'SynthBass 1 KA',
  'SynthBass 2 KA',
  'SynthBass 3 KA',
  'SynthBass 4 KA',
  'Analog Sweep KA',
  'Karplus KA',
  'KApro Pad KA',
  'Human Pad KA',
  'Motion Pad KA',
  'Hold On KA',
  'Ambi Growl KA',
  'Passport KA',
  'Brassy KA',
  'Warm Obey KA',
  'Sawyer Lead KA',
  "Let's Go KA",
  'Sweet Dreams KA',
  'Fat Bass KA',
  'Sad Slow KA',
  'Wobbles KA',
  'Funky Lead KA',
  'Modular FX KA',
  'Slow Drone KA',
  'Big Pad KA',
  'Calming KA',
  'Scan Pad KA',
  'KA Phase Pad KA',
  'Warm SAW KA',
  'Toy Room KA',
  'Dancing ARP KA',
  'Noise Bliss KA',
  'Retrigger KA',
  'Chaossss KA',
  'The Sign KA',
  'Rock On KA',
  'Locked Out 1 KA',
  'Locked Out 2 KA',
  'Slow Pad 1 KA',
  'Slow Pad 2 KA',
  'Punch Bass KA',
  'Shimmer KA',
  'Digilog KA',
  'Waverider KA',
  'Cathedral KA',
  'Humble Keys KA',
  'Soft Pad KA',
  'Ambiedream KA',
  'Distortian KA',
  'Polysynth 1 KA',
  'Polysynth 2 KA',
  'Aeronautics KA',
  'Mellow Pad KA',
  'Bank G',
  'Acid Bass KA',
  'Rhythm Steps KA',
  'LFO Pad KA',
  'Influx Pad KA',
  'Metal Pad KA',
  'Funk Synth KA',
  'Alien Pad 1 KA',
  'Alien Pad 2 KA',
  'Bell Pad KA',
  'Lift Up KA',
  'Myssa Drone KA',
  'Oxyda Pad KA',
  'Early Keys KA',
  'Wide Shut KA',
  'Chill Out KA',
  'Sigma Lead KA',
  'Telma ARP KA',
  'Multi Synth KA',
  'Portation KA',
  'Syncussion KA',
  'Westlead Pad KA',
  'Moving Mine KA',
  'New Age Pad KA',
  'Free Jazz KA',
  'Ominous MorphKA',
  'Wavetrance KA',
  'Key Off KA',
  'Organilog KA',
  'VCF Sweep KA',
  'FM Bells KA',
  'Powerful KA',
  'Angel Pad KA',
  'Fairy Steps KA',
  'FRANKnSTEIN KA',
  'Experience KA',
  'Nightmare KA',
  'VCF Zapp KA',
  'Epic Pad KA',
  'Mine Bells KA',
  'Tension SynthKA',
  'Got Rezzz KA',
  'Tomeso KA',
  'Evolving KA',
  'Interstellar KA',
  'Cinematic KA',
  'Klangzauber! KA',
  'Cyber Pad KA',
  'Main Synth KA',
  'Harpsichord KA',
  'Smooth Pad KA',
  'Bowed Wheel KA',
  'Harsh Bass KA',
  'Bubbles KA',
  'Relax & DreamKA',
  'Older Days KA',
  'Experimental KA',
  'Prismatic KA',
  'Massive KA',
  'War Games KA',
  'Bad Dreams KA',
  'LFO Planet KA',
  'Healing Pad KA',
  'Accordion KA',
  'Strings KA'
];

export const bankH = [
  'Rich Rises  DK',
  'Bass Punch DK',
  'Warm PadFX  DK',
  'MouseChord DK',
  'FilterWhip DK',
  'Pure Space DK',
  'OctaveSwel DK',
  'Random Arp DK',
  'Boards VHS DK',
  'Noise Perc DK',
  'Ouzo Bass  DK',
  'Square Lead DK',
  'Retro Swell DK',
  'Flutter Seq DK',
  'Acid Fiend  DK',
  'Neuro Fun   DK',
  'Velo Funk   DK',
  'House Chord DK',
  'Guitar Dirt DK',
  'Talking Res DK',
  'Silly Riser DK',
  'Arp Pluck   DK',
  'ChordCrunch DK',
  'Super Saws  DK',
  'FM Wonk     DK',
  'Wobble Bass DK',
  'Percussion  DK',
  'Vintage Pad DK',
  'Mono Sync   DK',
  'S&H ToneMod DK',
  'Pluk ModWet DK',
  'PWM Swell   DK',
  'ShimmerSwel DK',
  'Noiz Hit FX DK',
  'Chord Arp   DK',
  'FM F-Yeah   DK',
  'Vibro Funk  DK',
  'Filter FM   DK',
  'Alien Love  DK',
  'Dry Strings DK',
  'Keys        DK',
  'Organ WanaB DK',
  'Teacake Arp DK',
  'Mario Love  DK',
  '-2 Saw Sub  DK',
  'Major 10    DK',
  'Pad Chopper DK',
  'Tone Shift  DK',
  'Arcade 8ve  DK',
  'Poly Ramps  DK',
  'ModWheelArp DK',
  'Drifter     DK',
  'Unison Wash DK',
  'Alien Lands DK',
  'Noise Punch DK',
  'Click Delay DK',
  'Vintage LFO DK',
  'Wonky Toy   DK',
  'Soft Fifth  DK',
  'Clicky Bass DK',
  'Fidget Arp  DK',
  'Soft Swells DK',
  'Lost Verb   DK',
  'Env3 Overto DK',
  'Bank H',
  'Slasher     DK',
  'Movie Pad   DK',
  'S&H Filter  DK',
  'Falling LFO DK',
  'FX Wobbles  DK',
  'Bass Arp    DK',
  'DCO Harmony DK',
  'Broken Atom DK',
  'Verb Excite DK',
  '3 Way Mod   DK',
  'FadeIn RNDM DK',
  'Breaking FM DK',
  'Warped Perc DK',
  'Rez BandPas DK',
  'Saw Shimmer DK',
  'Soft Mono   DK',
  'Square Fun  DK',
  'Clean Keys  DK',
  '4Pole Pluck DK',
  'Synth Waves DK',
  'SyncToneMod DK',
  'Warm Arp    DK',
  'Bass Stomp  DK',
  'Filter Rise DK',
  'RND Swinger DK',
  'ModWheel FRZDK',
  'Mono Filth  DK',
  'Reso Rise   DK',
  'Simple Uni  DK',
  'Verb Trick  DK',
  'Bass Swells DK',
  'Over Reso   DK',
  'BigChord minDK',
  'Mellow      DK',
  'Bulbous Arp DK',
  'KeyPressRND DK',
  'Space Cave  DK',
  'NonStopLoop DK',
  'Fadin Dison DK',
  'Ice Drift   DK',
  'LFO SequenceDK',
  'Six Oh OnesiDK',
  'Clap        DK',
  'Floating ArpDK',
  'Odd EGs     DK',
  'ModW FX RiseDK',
  'Sync Mod PadDK',
  'OctaveBubbleDK',
  'Smooth NoiseDK',
  'Swellverb   DK',
  'Bass Throb  DK',
  'Space Lead  DK',
  'VintageDriftDK',
  'NuclearNoiseDK',
  'Mono Cloud  DK',
  'Serene Keys DK',
  'Thin2FullArpDK',
  'Mega Mod    DK',
  'ModulatedModDK',
  'Ramp Mods   DK',
  'Deep Space  DK',
  'Quirk Arp   DK',
  'Play Wheels DK',
  'Theme Pad   DK'
];

const deepmindPatches = {
  'Bank A': bankA,
  'Bank B': bankB,
  'Bank C': bankC,
  'Bank D': bankD,
  'Bank E': bankE,
  'Bank F': bankF,
  'Bank G': bankG,
  'Bank H': bankH
};

export default deepmindPatches;
